[package]
name = "pts_bomber"
version = "1.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.7", features = ["json", "cookies"] }
tokio = { version = "1.40.0", features = ["full"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
hardware-id = "0.3.0"
