name: Rust

on:
  push:
    tags:
      - '*'
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_upload_ubuntu:
    name: Build and upload Ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Install OS dependencies
        run: |
          sudo apt update
          sudo apt install libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Install create-tauri-app
        run: cargo install --locked create-tauri-app
      - name: Install tauri-cli
        run: cargo install --locked tauri-cli
      - name: Install trunk
        run: cargo install --locked trunk
      - name: Install wasm-bindgen-cli
        run: cargo install --locked wasm-bindgen-cli
      - name: Install cargo-leptos
        run: cargo install --locked cargo-leptos
      - name: Install target
        run: rustup target add wasm32-unknown-unknown

      - name: Build
        run: cargo tauri build

      - name: Upload
        uses: actions/upload-artifact@v4.4.3
        with:
          name: 'pts_bomber_ubuntu'
          path: |
            **/pts_bomber
            **/pts_bomber_*_amd64.deb
            **/pts_bomber-*.x86_64.rpm
  build_upload_windows:
    name: Build and upload Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Install OS dependencies
        run: rustup default stable-msvc

      - name: Install create-tauri-app
        run: cargo install --locked create-tauri-app
      - name: Install tauri-cli
        run: cargo install --locked tauri-cli
      - name: Install trunk
        run: cargo install --locked trunk
      - name: Install wasm-bindgen-cli
        run: cargo install --locked wasm-bindgen-cli
      - name: Install cargo-leptos
        run: cargo install --locked cargo-leptos
      - name: Install target
        run: rustup target add wasm32-unknown-unknown

      - name: Build
        run: cargo tauri build

      - name: Upload
        uses: actions/upload-artifact@v4.4.3
        with:
          name: 'pts_bomber_windows'
          path: |
            **/pts_bomber.exe
            **/pts_bomber_2.0.0-*_x64-setup.exe
  build_upload_macos:
    name: Build and upload macOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Install create-tauri-app
        run: cargo install --locked create-tauri-app
      - name: Install tauri-cli
        run: cargo install --locked tauri-cli
      - name: Install trunk
        run: cargo install --locked trunk
      - name: Install wasm-bindgen-cli
        run: cargo install --locked wasm-bindgen-cli
      - name: Install cargo-leptos
        run: cargo install --locked cargo-leptos
      - name: Install target
        run: rustup target add wasm32-unknown-unknown

      - name: Build
        run: cargo tauri build

      - name: Upload
        uses: actions/upload-artifact@v4.4.3
        with:
          name: 'pts_bomber_macos'
          path: |
            **/pts_bomber
            **/pts_bomber.app
            **/pts_bomber_*_aarch64.dmg
